#!/bin/bash
# Turns the firewall on
sudo ufw enable

# Enables port 22
sudo ufw allow 22

# Enables port 80
sudo ufw allow 80

# Enables port 443
sudo ufw allow 443

# Checks firewall status
sudo ufw status
